# Document:
# http://simiki.org/docs/configuration.html

url: http://wiekern.github.io/wiki 
title: wikern's WIKI
keywords: Linux, Java, Android, Web 
description: 
author: wieKern
root: /wiki/

default_ext: md
pygments: true
debug: false

deploy:
  - type: git
    remote: origin
    branch: gh-pages
