# Document:
# http://simiki.org/docs/configuration.html

url: http://wiekern.github.io 
title: wiekernWiki
keywords: 
description: 
author: wieKern

default_ext: md
pygments: true
debug: false

deploy:
  - type: git
    remote: origin
    branch: gh-pages
